# Generated by Django 4.2.16 on 2024-09-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
