# Generated by Django 4.2.16 on 2024-09-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task_options_rename_complete_task_completed'),
        ('todo', '0005_alter_task_options_rename_complete_task_completed'),
    ]

    operations = [
    ]
